export default {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILURE:'LOGIN_FAILURE',

    REGISTRATION_REQUEST:'REGISTRATION_REQUEST',
    REGISTRATION_SUCCESS:'REGISTRATION_SUCCESS',
    REGISTRATION_FAILURE:'REGISTRATION_FAILURE',
}