import CATEGORY_ACTIONS from './Category';
import PRODUCTS_ACTIONS from './Products';
import PRODUCT_DETAIL_ACTIONS from './productDetail';
import WEBCOLLECTION_ACTIONS from './WebCollection';
import GETPRODUCTSBYWEBCOLLECTION_ACTIONS from './GetProductsByWebCollection';
import PRODUCT_CATEGORY_ACTIONS from './ProductCategory';
import PRODUCT_COMPARISON_ACTIONS from './ProductComparsion';
import LOGIN_ACTIONS from './Auth';
import WISHLIST_ACTIONS from './WishList';
import HOME_ACTIONS from './Home';

export {
    CATEGORY_ACTIONS,
    PRODUCTS_ACTIONS,
    PRODUCT_DETAIL_ACTIONS,
    WEBCOLLECTION_ACTIONS,
    GETPRODUCTSBYWEBCOLLECTION_ACTIONS,
    PRODUCT_CATEGORY_ACTIONS,
    PRODUCT_COMPARISON_ACTIONS,
    LOGIN_ACTIONS,
    WISHLIST_ACTIONS,
    HOME_ACTIONS,
}