export default {
    GET_PRODUCT_COMAPARSION_REQUEST: 'GET_PRODUCT_COMAPARSION_REQUEST',
    GET_PRODUCT_COMAPARSION_SUCCESS: 'GET_PRODUCT_COMAPARSION_SUCCESS',
    GET_PRODUCT_COMAPARSION_FAILURE: 'GET_PRODUCT_COMAPARSION_FAILURE'
} 