export default {
    GET_PRODUCTS_REQUEST: 'GET_PRODUCTS_REQUEST',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAILURE: 'GET_PRODUCTS_FAILURE',

    GET_PRODUCTSBY_WEBCOLLECTION_REQUEST: 'GET_PRODUCTSBY_WEBCOLLECTION_REQUEST',
    GET_PRODUCTSBY_WEBCOLLECTION_SUCCESS: 'GET_PRODUCTSBY_WEBCOLLECTION_SUCCESS',
    GET_PRODUCTSBY_WEBCOLLECTION_FAILURE: 'GET_PRODUCTSBY_WEBCOLLECTION_FAILURE',
} 