export default {
    GET_PRODUCT_BRAND_CATEGORY_REQUEST: 'GET_PRODUCT_BRAND_CATEGORY_REQUEST',
    GET_PRODUCT_BRAND_CATEGORY_SUCCESS: 'GET_PRODUCT_BRAND_CATEGORY_SUCCESS',
    GET_PRODUCT_BRAND_CATEGORY_FAILURE: 'GET_PRODUCT_BRAND_CATEGORY_FAILURE',
}