export default {
    GET_WISHLIST_REQUEST: 'GET_WISHLIST_REQUEST',
    GET_WISHLIST_SUCCESS: 'GET_WISHLIST_SUCCESS',
    GET_WISHLIST_FAILURE: 'GET_WISHLIST_FAILURE',

    POST_WISHLIST_REQUEST: 'POST_WISHLIST_REQUEST',
    POST_WISHLIST_SUCCESS: 'POST_WISHLIST_SUCCESS',
    POST_WISHLIST_FAILURE: 'POST_WISHLIST_FAILURE',

    UPDATE_WISHLIST_REQUEST: 'UPDATE_WISHLIST_REQUEST',
    UPDATE_WISHLIST_SUCCESS: 'UPDATE_WISHLIST_SUCCESS',
    UPDATE_WISHLIST_FAILURE: 'UPDATE_WISHLIST_FAILURE',

    DELETE_WISHLIST_REQUEST: 'DELETE_WISHLIST_REQUEST',
    DELETE_WISHLIST_SUCCESS: 'DELETE_WISHLIST_SUCCESS',
    DELETE_WISHLIST_FAILURE: 'DELETE_WISHLIST_FAILURE',
}