export const URLS = {
    GET_CATEGORY: '/api/productType',
    GET_PRODUCTS: '/api/products/type/',
    GET_PRODUCT_DETAIL: '/api/products/',
    GET_WEBCOLLECTION: '/api/webcollections/',
    GET_PRODUCTBYWEBCOLLECTION: '/api/products/type/',
    GET_PRODUCT_BRAND_CATEGORY: '/api/products/categories',
    GET_PRODUCT_COMPARISON: '/api/productCompare/',
    GET_WISHLIST: '/api/wishList/user/',
    POST_WISHLIST: '/api/wishList/',
    UPDATE_WISHlIST: '/api/wishList/updateWishList/',
    DELETE_WISHLISH: '/api/wishList/deleteWishList/',
    LOGIN: '/api/auth/',
    REGISTER: '/api/users/',
    HOME: '/api/products/home',
};